unicode_ranges = {
    "Basic Latin": {"first_including": 0x0000, "last_including": 0x007F},
    "Latin-1 Supplement": {"first_including": 0x0080, "last_including": 0x00FF},
    "Latin Extended-A": {"first_including": 0x0100, "last_including": 0x017F},
    "Latin Extended-B": {"first_including": 0x0180, "last_including": 0x024F},
    "IPA Extensions": {"first_including": 0x0250, "last_including": 0x02AF},
    "Spacing Modifier Letters": {"first_including": 0x02B0, "last_including": 0x02FF},
    "Combining Diacritical Marks": {"first_including": 0x0300, "last_including": 0x036F},
    "Greek and Coptic": {"first_including": 0x0370, "last_including": 0x03FF},
    "Cyrillic": {"first_including": 0x0400, "last_including": 0x04FF},
    "Cyrillic Supplement": {"first_including": 0x0500, "last_including": 0x052F},
    "Hangul Jamo": {"first_including": 0x1100, "last_including": 0x11FF},
    "Latin Extended Additional": {"first_including": 0x1E00, "last_including": 0x1EFF},
    "Greek Extended": {"first_including": 0x1F00, "last_including": 0x1FFF},
    "General Punctuation": {"first_including": 0x2000, "last_including": 0x206F},
    "Superscripts and Subscripts": {"first_including": 0x2070, "last_including": 0x209F},
    "Currency Symbols": {"first_including": 0x20A0, "last_including": 0x20CF},
    "Combining Diacritical Marks for Symbols": {"first_including": 0x20D0, "last_including": 0x20FF},
    "Letterlike Symbols": {"first_including": 0x2100, "last_including": 0x214F},
    "Number Forms": {"first_including": 0x2150, "last_including": 0x218F},
    "Arrows": {"first_including": 0x2190, "last_including": 0x21FF},
    "Mathematical Operators": {"first_including": 0x2200, "last_including": 0x22FF},
    "Miscellaneous Technical": {"first_including": 0x2300, "last_including": 0x23FF},
    "Control Pictures": {"first_including": 0x2400, "last_including": 0x243F},
    "Optical Character Recognition": {"first_including": 0x2440, "last_including": 0x245F},
    "Enclosed Alphanumerics": {"first_including": 0x2460, "last_including": 0x24FF},
    "Box Drawing": {"first_including": 0x2500, "last_including": 0x257F},
    "Block Elements": {"first_including": 0x2580, "last_including": 0x259F},
    "Geometric Shapes": {"first_including": 0x25A0, "last_including": 0x25FF},
    "Miscellaneous Symbols": {"first_including": 0x2600, "last_including": 0x26FF},
    "Dingbats": {"first_including": 0x2700, "last_including": 0x27BF},
    "Miscellaneous Mathematical Symbols-A": {"first_including": 0x27C0, "last_including": 0x27EF},
    "Supplemental Arrows-A": {"first_including": 0x27F0, "last_including": 0x27FF},
    "Braille Patterns": {"first_including": 0x2800, "last_including": 0x28FF},
    "Supplemental Arrows-B": {"first_including": 0x2900, "last_including": 0x297F},
    "Miscellaneous Mathematical Symbols-B": {"first_including": 0x2980, "last_including": 0x29FF},
    "Supplemental Mathematical Operators": {"first_including": 0x2A00, "last_including": 0x2AFF},
    "Miscellaneous Symbols and Arrows": {"first_including": 0x2B00, "last_including": 0x2BFF},
    "Latin Extended-C": {"first_including": 0x2C60, "last_including": 0x2C7F},
    "Cyrillic Extended-A": {"first_including": 0x2DE0, "last_including": 0x2DFF},
    "Supplemental Punctuation": {"first_including": 0x2E00, "last_including": 0x2E7F},
    "CJK Radicals Supplement": {"first_including": 0x2E80, "last_including": 0x2EFF},
    "Kangxi Radicals": {"first_including": 0x2F00, "last_including": 0x2FDF},
    "Ideographic Description Characters": {"first_including": 0x2FF0, "last_including": 0x2FFF},
    "CJK Symbols and Punctuation": {"first_including": 0x3000, "last_including": 0x303F},
    "Hiragana": {"first_including": 0x3040, "last_including": 0x309F},
    "Katakana": {"first_including": 0x30A0, "last_including": 0x30FF},
    "Bopomofo": {"first_including": 0x3100, "last_including": 0x312F},
    "Hangul Compatibility Jamo": {"first_including": 0x3130, "last_including": 0x318F},
    "Bopomofo Extended": {"first_including": 0x31A0, "last_including": 0x31BF},
    "CJK Strokes": {"first_including": 0x31C0, "last_including": 0x31EF},
    "Katakana Phonetic Extensions": {"first_including": 0x31F0, "last_including": 0x31FF},
    "Enclosed CJK Letters and Months": {"first_including": 0x3200, "last_including": 0x32FF},
    "CJK Compatibility": {"first_including": 0x3300, "last_including": 0x33FF},
    "CJK Unified Ideographs Extension A": {"first_including": 0x3400, "last_including": 0x4DBF},
    "Yijing Hexagram Symbols": {"first_including": 0x4DC0, "last_including": 0x4DFF},
    "CJK Unified Ideographs": {"first_including": 0x4E00, "last_including": 0x9FFF},
    "Yi Syllables": {"first_including": 0xA000, "last_including": 0xA48F},
    "Yi Radicals": {"first_including": 0xA490, "last_including": 0xA4CF},
    "Cyrillic Extended-B": {"first_including": 0xA640, "last_including": 0xA69F},
    "Modifier Tone Letters": {"first_including": 0xA700, "last_including": 0xA71F},
    "Latin Extended-D": {"first_including": 0xA720, "last_including": 0xA7FF},
    "Hangul Jamo Extended-A": {"first_including": 0xA960, "last_including": 0xA97F},
    "Latin Extended-E": {"first_including": 0xAB30, "last_including": 0xAB6F},
    "Hangul Syllables": {"first_including": 0xAC00, "last_including": 0xD7AF},
    "Hangul Jamo Extended-B": {"first_including": 0xD7B0, "last_including": 0xD7FF},
    "High Surrogates": {"first_including": 0xD800, "last_including": 0xDB7F},
    "High Private Use Surrogates": {"first_including": 0xDB80, "last_including": 0xDBFF},
    "Low Surrogates": {"first_including": 0xDC00, "last_including": 0xDFFF},
    "Private Use Area": {"first_including": 0xE000, "last_including": 0xF8FF},
    "CJK Compatibility Ideographs": {"first_including": 0xF900, "last_including": 0xFAFF},
    "Alphabetic Presentation Forms": {"first_including": 0xFB00, "last_including": 0xFB4F},
    "Vertical Forms": {"first_including": 0xFE10, "last_including": 0xFE1F},
    "Combining Half Marks": {"first_including": 0xFE20, "last_including": 0xFE2F},
    "CJK Compatibility Forms": {"first_including": 0xFE30, "last_including": 0xFE4F},
    "Small Form Variants": {"first_including": 0xFE50, "last_including": 0xFE6F},
    "Halfwidth and Fullwidth Forms": {"first_including": 0xFF00, "last_including": 0xFFEF},
    "Specials": {"first_including": 0xFFF0, "last_including": 0xFFFF},
}


def get_mask(unicode_ranges):

    mask = {}

    for i in range(2 ** 16):
        mask[i] = False

        for r in unicode_ranges:
            if unicode_ranges[r]['first_including'] <= i <= unicode_ranges[r]['last_including']:
                mask[i] = True
    
    return mask

ignore_mask = get_mask(unicode_ranges)
